---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-cm
  namespace: code-ns
  labels:
    app: code
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-159.89.211.156.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: code-secret
  namespace: code-ns
  labels:
    app: code
type: Opaque
data:
  # changeit
  PASSWORD: Y2hhbmdlaXQ=
  SUDO_PASSWORD: Y2hhbmdlaXQ=

