apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"app":"dov-bear","env":"development"},"name":"dev-ns"}}
    labels:
      app: dov-bear
      env: development
    name: dev-ns
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"dov-bear","env":"development"},"name":"dev-dov-svc-team1","namespace":"dev-ns"},"spec":{"ports":[{"port":8080,"targetPort":3000}],"selector":{"app":"dov-bear","env":"development","name":"dov-po"},"type":"ClusterIP"}}
    labels:
      app: dov-bear
      env: development
    name: dev-dov-svc-team1
    namespace: dev-ns
  spec:
    ports:
    - port: 8080
      targetPort: 3000
    selector:
      app: dov-bear
      env: development
      name: dov-po
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"dov-bear","env":"development"},"name":"dev-dov-deploy-team1","namespace":"dev-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"dov-bear","env":"development","name":"dov-po"}},"template":{"metadata":{"labels":{"app":"dov-bear","env":"development","name":"dov-po"},"name":"dov-po"},"spec":{"containers":[{"env":[{"name":"INSTANCE_NAME","value":"dov-bear"},{"name":"INSTANCE_HASH","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"chukmunnlee/dov-bear:v4","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/healthz","port":3000}},"name":"my-container","ports":[{"containerPort":3000}]}]}}}}
    labels:
      app: dov-bear
      env: development
    name: dev-dov-deploy-team1
    namespace: dev-ns
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: dov-bear
        env: development
        name: dov-po
    template:
      metadata:
        labels:
          app: dov-bear
          env: development
          name: dov-po
        name: dov-po
      spec:
        containers:
        - env:
          - name: INSTANCE_NAME
            value: dov-bear
          - name: INSTANCE_HASH
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          image: chukmunnlee/dov-bear:v4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          name: my-container
          ports:
          - containerPort: 3000
kind: List
metadata: {}
