apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 

resources:
- ../../base

commonLabels:
  env: development

namespace: dev-ns

namePrefix: dev- 
nameSuffix: -team1

replicas:
- name: dov-deploy 
  count: 1

images:
- name: chukmunnlee/dov-bear
  newTag: v4

patches:
- target:
    version: v1
    kind: Service 
    name: dov-svc 
  # https://jsonpatch.com/
  path: patch-svc.yaml