---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
  labels:
    app: minio
    name: minio-cm
data:
  MINIO_ROOT_USER: admin

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
  labels:
    app: minio
    name: minio-secret
type: Opaque
data:
  # adminadmin
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg==
