---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: 
  name: dov-bear-ro
  namespace: dov-ns
  labels:
    app: dov-bear
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dov-deploy
  strategy:
    blueGreen:
      activeService: dov-svc
      previewService: dov-svc-preview
      autoPromotionEnabled: false
